import type { Metadata } from 'next';
import type { FontDetail } from '@/models/fontDetail';
import { GET } from '@/app/api/familyDetails';
import CardFontDetailComponent from '@/app/components/cards/fontDetail';

// génération des métadonnées dynamiques pour chaque page de police
export const metadata: Metadata = {
  title: '{foundry.name} {name}',
  description: 'Generated by create next app',
};

// fonction pour récupérer les données de la police depuis l'API
async function fetchData() {
  const res = await GET();
  const data: FontDetail = await res.json();
  return { data };
}

export default async function FontPage() {
  const { data } = await fetchData();
  metadata.title = `${data.foundry.name} ${data.name}`;

  return <CardFontDetailComponent item={data} />;
}
